services:
  - type: web
    name: order-management-ui
    env: node
    rootDir: order
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16.17.0
